#!/bin/bash

curl -o setup_agent.sh https://setup.instana.io/agent && chmod 700 ./setup_agent.sh && sudo ./setup_agent.sh -a qUMhYJxjSv6uZh2SyqTEnw -d qUMhYJxjSv6uZh2SyqTEnw -t dynamic -e 67.228.227.210:1444   


systemctl start instana-agent.service
systemctl enable instana-agent.service
systemctl status instana-agent.service
        
Infrastucture Map shows
